version: '2'

services:
    web:
        #image: nginx:latest
        image: us.gcr.io/sgc-gke-tutorial/nginx
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/site.conf
    php:
        #image: php:7-fpm
        image: us.gcr.io/sgc-gke-tutorial/php7
        volumes:
            - ./code:/code
            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
