apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    name: demo
spec:
  containers:
    - name: webserver
      # TODO: set this with your zone and project id
      image: "nginx:latest"
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          protocol: TCP

    - name: php
      # TODO: set this with your zone and project id
      image: "php:7-fpm"
      imagePullPolicy: Always
